import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar' | 'es';

interface TranslationParams {
  [key: string]: string | number;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: TranslationParams) => string;
}

const translations = {
  en: {
    // Common
    appName: 'CeramControl',
    dashboard: 'Dashboard',
    batches: 'Production Batches',
    qualityControl: 'Quality Control',
    reports: 'Reports',
    analytics: 'Analytics',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    
    // Quality Control
    qualityControlTitle: 'Quality Control',
    qualityControlDesc: 'Record quality measurements and document visual defects',
    physicalMeasurements: 'Physical Measurements',
    visualDefects: 'Visual Defects',
    recordQualityMeasurement: 'Record Quality Measurement',
    batch: 'Batch',
    batchId: 'Batch ID',
    selectBatch: 'Select a batch',
    parameter: 'Parameter',
    selectParameter: 'Select a quality parameter',
    measurementValue: 'Measurement Value',
    isoStandard: 'ISO Standard',
    reset: 'Reset',
    recordMeasurement: 'Record Measurement',
    recording: 'Recording...',
    
    // Analytics
    passingRate: 'Passing Rate',
    failureRate: 'Failure Rate',
    unknown: 'Unknown',
    analyticsDescription: 'Quality metrics and production performance analytics',
    qualityTrends: 'Quality Trends',
    overTimeAnalysis: 'Analysis over time',
    defectDistribution: 'Defect Distribution',
    byTypeAnalysis: 'Analysis by defect type',
    productionPerformance: 'Production Performance',
    batchComparisonAnalysis: 'Batch comparison analysis',
    detailedAnalytics: 'Detailed Analytics',
    detailedAnalyticsDescription: 'In-depth analysis of quality and production metrics',
    qualityMetrics: 'Quality Metrics',
    productionMetrics: 'Production Metrics',
    complianceMetrics: 'Compliance Metrics',
    week: 'Week',
    month: 'Month',
    quarter: 'Quarter',
    year: 'Year',
    
    // Batches
    productionBatches: 'Production Batches',
    batchesDescription: 'Manage and monitor production quality by batch',
    createBatch: 'Create Batch',
    search: 'Search',
    batchInformation: 'Batch Information',
    productionDate: 'Production Date',
    kiln: 'Kiln',
    materialLot: 'Material Lot',
    createdBy: 'Created By',
    latestMeasurements: 'Latest Measurements',
    recentQualityControlMeasurements: 'Recent quality control measurements',
    reportedDefects: 'Reported Defects',
    visualAndPhysicalDefects: 'Visual and physical defects',
    measurements: 'Measurements',
    defects: 'Defects',
    actions: 'Actions',
    correctiveActions: 'Corrective Actions',
    qualityControlMeasurements: 'Quality Control Measurements',
    measurementsAgainstISOStandards: 'Measurements against ISO standards',
    min: 'Min',
    max: 'Max',
    status: 'Status',
    measuredBy: 'Measured By',
    date: 'Date',
    type: 'Type',
    severity: 'Severity',
    catalogedDefectsWithImages: 'Cataloged defects with images',
    reportedOn: 'Reported on',
    noDefectsReported: 'No defects reported',
    noDefectsReportedForBatch: 'No defects reported for this batch',
    recommendedActionsForNonCompliant: 'Recommended actions for non-compliant measurements',
    noCorrectiveActionsNeeded: 'No corrective actions needed',
    value: 'Value',
    currentValue: 'Current Value',
    requiredRange: 'Required Range',
    recommendedAction: 'Recommended Action',
    addMeasurement: 'Add Measurement',
    reportDefect: 'Report Defect',
    generateReport: 'Generate Report',
    overview: 'Overview',
    compliant: 'Compliant',
    nonCompliant: 'Non-compliant',
    pass: 'Pass',
    warnings: 'Warnings',
    failures: 'Failures',
    isoCompliance: 'ISO Compliance',
    
    // Settings
    appSettings: 'App Settings',
    appSettingsDescription: 'Configure application settings and preferences',
    companyName: 'Company Name',
    defaultLanguage: 'Default Language',
    selectLanguage: 'Select Language',
    dateFormat: 'Date Format',
    selectDateFormat: 'Select Date Format',
    darkMode: 'Dark Mode',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    settingsSaved: 'Settings Saved',
    settingsSavedSuccess: 'Your settings have been updated successfully',
    notificationPreferences: 'Notification Preferences',
    notificationPreferencesDescription: 'Configure when and how you receive notifications',
    batchFailureAlerts: 'Batch Failure Alerts',
    batchFailureAlertsDescription: 'Get notified when a batch fails quality control',
    qualityThresholdAlerts: 'Quality Threshold Alerts',
    qualityThresholdAlertsDescription: 'Get notified when measurements approach critical thresholds',
    newReportNotifications: 'New Report Notifications',
    newReportNotificationsDescription: 'Get notified when new quality reports are generated',
    systemUpdates: 'System Updates',
    systemUpdatesDescription: 'Get notified about system updates and maintenance',
    notificationsSaved: 'Notifications Saved',
    notificationsSavedSuccess: 'Your notification preferences have been updated successfully',
    
    // Other
    unitOfMeasure: 'Unit of Measure',
    description: 'Description',
    image: 'Image',
    uploadImage: 'Upload Image',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    finish: 'Finish',
  },
  fr: {
    // Common
    appName: 'CeramControl',
    dashboard: 'Tableau de bord',
    batches: 'Lots de production',
    qualityControl: 'Contrôle qualité',
    reports: 'Rapports',
    analytics: 'Analyses',
    settings: 'Paramètres',
    profile: 'Profil',
    logout: 'Déconnexion',
    
    // Quality Control
    qualityControlTitle: 'Contrôle qualité',
    qualityControlDesc: 'Enregistrer les mesures de qualité et documenter les défauts visuels',
    physicalMeasurements: 'Mesures physiques',
    visualDefects: 'Défauts visuels',
    recordQualityMeasurement: 'Enregistrer une mesure de qualité',
    batch: 'Lot',
    batchId: 'ID du lot',
    selectBatch: 'Sélectionner un lot',
    parameter: 'Paramètre',
    selectParameter: 'Sélectionner un paramètre de qualité',
    measurementValue: 'Valeur de mesure',
    isoStandard: 'Norme ISO',
    reset: 'Réinitialiser',
    recordMeasurement: 'Enregistrer la mesure',
    recording: 'Enregistrement...',
    
    // Analytics
    passingRate: 'Taux de réussite',
    failureRate: 'Taux d\'échec',
    unknown: 'Inconnu',
    analyticsDescription: 'Métriques de qualité et analyse de la performance de production',
    qualityTrends: 'Tendances de qualité',
    overTimeAnalysis: 'Analyse dans le temps',
    defectDistribution: 'Distribution des défauts',
    byTypeAnalysis: 'Analyse par type de défaut',
    productionPerformance: 'Performance de production',
    batchComparisonAnalysis: 'Analyse comparative des lots',
    detailedAnalytics: 'Analyses détaillées',
    detailedAnalyticsDescription: 'Analyse approfondie des métriques de qualité et de production',
    qualityMetrics: 'Métriques de qualité',
    productionMetrics: 'Métriques de production',
    complianceMetrics: 'Métriques de conformité',
    week: 'Semaine',
    month: 'Mois',
    quarter: 'Trimestre',
    year: 'Année',
    
    // Batches
    productionBatches: 'Lots de production',
    batchesDescription: 'Gérer et surveiller la qualité de production par lot',
    createBatch: 'Créer un lot',
    search: 'Rechercher',
    batchInformation: 'Informations sur le lot',
    productionDate: 'Date de production',
    kiln: 'Four',
    materialLot: 'Lot de matériau',
    createdBy: 'Créé par',
    latestMeasurements: 'Dernières mesures',
    recentQualityControlMeasurements: 'Mesures récentes de contrôle qualité',
    reportedDefects: 'Défauts signalés',
    visualAndPhysicalDefects: 'Défauts visuels et physiques',
    measurements: 'Mesures',
    defects: 'Défauts',
    actions: 'Actions',
    correctiveActions: 'Actions correctives',
    qualityControlMeasurements: 'Mesures de contrôle qualité',
    measurementsAgainstISOStandards: 'Mesures selon les normes ISO',
    min: 'Min',
    max: 'Max',
    status: 'Statut',
    measuredBy: 'Mesuré par',
    date: 'Date',
    type: 'Type',
    severity: 'Sévérité',
    catalogedDefectsWithImages: 'Défauts catalogués avec images',
    reportedOn: 'Signalé le',
    noDefectsReported: 'Aucun défaut signalé',
    noDefectsReportedForBatch: 'Aucun défaut signalé pour ce lot',
    recommendedActionsForNonCompliant: 'Actions recommandées pour les mesures non conformes',
    noCorrectiveActionsNeeded: 'Aucune action corrective nécessaire',
    value: 'Valeur',
    currentValue: 'Valeur actuelle',
    requiredRange: 'Plage requise',
    recommendedAction: 'Action recommandée',
    addMeasurement: 'Ajouter une mesure',
    reportDefect: 'Signaler un défaut',
    generateReport: 'Générer un rapport',
    overview: 'Aperçu',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    pass: 'Réussite',
    warnings: 'Avertissements',
    failures: 'Échecs',
    isoCompliance: 'Conformité ISO',
    
    // Settings
    appSettings: 'Paramètres de l\'application',
    appSettingsDescription: 'Configurer les paramètres et les préférences de l\'application',
    companyName: 'Nom de l\'entreprise',
    defaultLanguage: 'Langue par défaut',
    selectLanguage: 'Sélectionner une langue',
    dateFormat: 'Format de date',
    selectDateFormat: 'Sélectionner un format de date',
    darkMode: 'Mode sombre',
    saving: 'Enregistrement...',
    saveChanges: 'Enregistrer les modifications',
    settingsSaved: 'Paramètres enregistrés',
    settingsSavedSuccess: 'Vos paramètres ont été mis à jour avec succès',
    notificationPreferences: 'Préférences de notification',
    notificationPreferencesDescription: 'Configurer quand et comment vous recevez des notifications',
    batchFailureAlerts: 'Alertes d\'échec de lot',
    batchFailureAlertsDescription: 'Être notifié lorsqu\'un lot échoue au contrôle qualité',
    qualityThresholdAlerts: 'Alertes de seuil de qualité',
    qualityThresholdAlertsDescription: 'Être notifié lorsque les mesures approchent des seuils critiques',
    newReportNotifications: 'Notifications de nouveaux rapports',
    newReportNotificationsDescription: 'Être notifié lorsque de nouveaux rapports de qualité sont générés',
    systemUpdates: 'Mises à jour du système',
    systemUpdatesDescription: 'Être notifié des mises à jour et de la maintenance du système',
    notificationsSaved: 'Notifications enregistrées',
    notificationsSavedSuccess: 'Vos préférences de notification ont été mises à jour avec succès',
    
    // Other
    unitOfMeasure: 'Unité de mesure',
    description: 'Description',
    image: 'Image',
    uploadImage: 'Télécharger une image',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    confirm: 'Confirmer',
    back: 'Retour',
    next: 'Suivant',
    finish: 'Terminer',
  },
  ar: {
    // Common
    appName: 'سيرامكونترول',
    dashboard: 'لوحة التحكم',
    batches: 'دفعات الإنتاج',
    qualityControl: 'مراقبة الجودة',
    reports: 'التقارير',
    analytics: 'التحليلات',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    
    // Quality Control
    qualityControlTitle: 'مراقبة الجودة',
    qualityControlDesc: 'تسجيل قياسات الجودة وتوثيق العيوب المرئية',
    physicalMeasurements: 'القياسات الفيزيائية',
    visualDefects: 'العيوب المرئية',
    recordQualityMeasurement: 'تسجيل قياس الجودة',
    batch: 'دفعة',
    batchId: 'رقم الدفعة',
    selectBatch: 'اختر دفعة',
    parameter: 'معيار',
    selectParameter: 'اختر معيار الجودة',
    measurementValue: 'قيمة القياس',
    isoStandard: 'معيار الأيزو',
    reset: 'إعادة تعيين',
    recordMeasurement: 'تسجيل القياس',
    recording: 'جاري التسجيل...',
    
    // Analytics
    passingRate: 'معدل النجاح',
    failureRate: 'معدل الفشل',
    unknown: 'غير معروف',
    analyticsDescription: 'مقاييس الجودة وتحليل أداء الإنتاج',
    qualityTrends: 'اتجاهات الجودة',
    overTimeAnalysis: 'التحليل عبر الزمن',
    defectDistribution: 'توزيع العيوب',
    byTypeAnalysis: 'تحليل حسب نوع العيب',
    productionPerformance: 'أداء الإنتاج',
    batchComparisonAnalysis: 'تحليل مقارنة الدفعات',
    detailedAnalytics: 'تحليلات مفصلة',
    detailedAnalyticsDescription: 'تحليل متعمق لمقاييس الجودة والإنتاج',
    qualityMetrics: 'مقاييس الجودة',
    productionMetrics: 'مقاييس الإنتاج',
    complianceMetrics: 'مقاييس الامتثال',
    week: 'أسبوع',
    month: 'شهر',
    quarter: 'ربع سنة',
    year: 'سنة',
    
    // Batches
    productionBatches: 'دفعات الإنتاج',
    batchesDescription: 'إدارة ومراقبة جودة الإنتاج حسب الدفعة',
    createBatch: 'إنشاء دفعة',
    search: 'بحث',
    batchInformation: 'معلومات الدفعة',
    productionDate: 'تاريخ الإنتاج',
    kiln: 'الفرن',
    materialLot: 'دفعة المواد',
    createdBy: 'أنشئت بواسطة',
    latestMeasurements: 'أحدث القياسات',
    recentQualityControlMeasurements: 'قياسات مراقبة الجودة الأخيرة',
    reportedDefects: 'العيوب المبلغ عنها',
    visualAndPhysicalDefects: 'العيوب المرئية والفيزيائية',
    measurements: 'القياسات',
    defects: 'العيوب',
    actions: 'الإجراءات',
    correctiveActions: 'الإجراءات التصحيحية',
    qualityControlMeasurements: 'قياسات مراقبة الجودة',
    measurementsAgainstISOStandards: 'القياسات وفقاً لمعايير الأيزو',
    min: 'الحد الأدنى',
    max: 'الحد الأقصى',
    status: 'الحالة',
    measuredBy: 'تم القياس بواسطة',
    date: 'التاريخ',
    type: 'النوع',
    severity: 'الخطورة',
    catalogedDefectsWithImages: 'العيوب المفهرسة مع الصور',
    reportedOn: 'أبلغ في',
    noDefectsReported: 'لا توجد عيوب مبلغ عنها',
    noDefectsReportedForBatch: 'لا توجد عيوب مبلغ عنها لهذه الدفعة',
    recommendedActionsForNonCompliant: 'الإجراءات الموصى بها للقياسات غير المتوافقة',
    noCorrectiveActionsNeeded: 'لا حاجة لإجراءات تصحيحية',
    value: 'القيمة',
    currentValue: 'القيمة الحالية',
    requiredRange: 'النطاق المطلوب',
    recommendedAction: 'الإجراء الموصى به',
    addMeasurement: 'إضافة قياس',
    reportDefect: 'الإبلاغ عن عيب',
    generateReport: 'إنشاء تقرير',
    overview: 'نظرة عامة',
    compliant: 'متوافق',
    nonCompliant: 'غير متوافق',
    pass: 'نجاح',
    warnings: 'تحذيرات',
    failures: 'إخفاقات',
    isoCompliance: 'توافق الأيزو',
    
    // Settings
    appSettings: 'إعدادات التطبيق',
    appSettingsDescription: 'تكوين إعدادات وتفضيلات التطبيق',
    companyName: 'اسم الشركة',
    defaultLanguage: 'اللغة الافتراضية',
    selectLanguage: 'اختر اللغة',
    dateFormat: 'تنسيق التاريخ',
    selectDateFormat: 'اختر تنسيق التاريخ',
    darkMode: 'الوضع المظلم',
    saving: 'جاري الحفظ...',
    saveChanges: 'حفظ التغييرات',
    settingsSaved: 'تم حفظ الإعدادات',
    settingsSavedSuccess: 'تم تحديث إعداداتك بنجاح',
    notificationPreferences: 'تفضيلات الإشعارات',
    notificationPreferencesDescription: 'تكوين وقت وكيفية تلقي الإشعارات',
    batchFailureAlerts: 'تنبيهات فشل الدفعة',
    batchFailureAlertsDescription: 'تلقي إشعار عند فشل دفعة في مراقبة الجودة',
    qualityThresholdAlerts: 'تنبيهات عتبة الجودة',
    qualityThresholdAlertsDescription: 'تلقي إشعار عندما تقترب القياسات من العتبات الحرجة',
    newReportNotifications: 'إشعارات التقارير الجديدة',
    newReportNotificationsDescription: 'تلقي إشعار عند إنشاء تقارير جودة جديدة',
    systemUpdates: 'تحديثات النظام',
    systemUpdatesDescription: 'تلقي إشعار حول تحديثات النظام والصيانة',
    notificationsSaved: 'تم حفظ الإشعارات',
    notificationsSavedSuccess: 'تم تحديث تفضيلات الإشعارات الخاصة بك بنجاح',
    
    // Other
    unitOfMeasure: 'وحدة القياس',
    description: 'الوصف',
    image: 'الصورة',
    uploadImage: 'تحميل صورة',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    finish: 'إنهاء',
  },
  es: {
    // Common
    appName: 'CeramControl',
    dashboard: 'Tablero',
    batches: 'Lotes de producción',
    qualityControl: 'Control de calidad',
    reports: 'Informes',
    analytics: 'Análisis',
    settings: 'Configuración',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    
    // Quality Control
    qualityControlTitle: 'Control de calidad',
    qualityControlDesc: 'Registrar medidas de calidad y documentar defectos visuales',
    physicalMeasurements: 'Medidas físicas',
    visualDefects: 'Defectos visuales',
    recordQualityMeasurement: 'Registrar medida de calidad',
    batch: 'Lote',
    batchId: 'ID del lote',
    selectBatch: 'Seleccionar un lote',
    parameter: 'Parámetro',
    selectParameter: 'Seleccionar un parámetro de calidad',
    measurementValue: 'Valor de medida',
    isoStandard: 'Estándar ISO',
    reset: 'Restablecer',
    recordMeasurement: 'Registrar medida',
    recording: 'Registrando...',
    
    // Analytics
    passingRate: 'Tasa de aprobación',
    failureRate: 'Tasa de fallo',
    unknown: 'Desconocido',
    analyticsDescription: 'Métricas de calidad y análisis de rendimiento de producción',
    qualityTrends: 'Tendencias de calidad',
    overTimeAnalysis: 'Análisis a lo largo del tiempo',
    defectDistribution: 'Distribución de defectos',
    byTypeAnalysis: 'Análisis por tipo de defecto',
    productionPerformance: 'Rendimiento de producción',
    batchComparisonAnalysis: 'Análisis comparativo de lotes',
    detailedAnalytics: 'Análisis detallado',
    detailedAnalyticsDescription: 'Análisis en profundidad de métricas de calidad y producción',
    qualityMetrics: 'Métricas de calidad',
    productionMetrics: 'Métricas de producción',
    complianceMetrics: 'Métricas de cumplimiento',
    week: 'Semana',
    month: 'Mes',
    quarter: 'Trimestre',
    year: 'Año',
    
    // Batches
    productionBatches: 'Lotes de producción',
    batchesDescription: 'Gestionar y monitorear la calidad de producción por lote',
    createBatch: 'Crear lote',
    search: 'Buscar',
    batchInformation: 'Información del lote',
    productionDate: 'Fecha de producción',
    kiln: 'Horno',
    materialLot: 'Lote de material',
    createdBy: 'Creado por',
    latestMeasurements: 'Últimas medidas',
    recentQualityControlMeasurements: 'Medidas recientes de control de calidad',
    reportedDefects: 'Defectos reportados',
    visualAndPhysicalDefects: 'Defectos visuales y físicos',
    measurements: 'Medidas',
    defects: 'Defectos',
    actions: 'Acciones',
    correctiveActions: 'Acciones correctivas',
    qualityControlMeasurements: 'Medidas de control de calidad',
    measurementsAgainstISOStandards: 'Medidas según estándares ISO',
    min: 'Mín',
    max: 'Máx',
    status: 'Estado',
    measuredBy: 'Medido por',
    date: 'Fecha',
    type: 'Tipo',
    severity: 'Severidad',
    catalogedDefectsWithImages: 'Defectos catalogados con imágenes',
    reportedOn: 'Reportado el',
    noDefectsReported: 'No hay defectos reportados',
    noDefectsReportedForBatch: 'No hay defectos reportados para este lote',
    recommendedActionsForNonCompliant: 'Acciones recomendadas para medidas no conformes',
    noCorrectiveActionsNeeded: 'No se necesitan acciones correctivas',
    value: 'Valor',
    currentValue: 'Valor actual',
    requiredRange: 'Rango requerido',
    recommendedAction: 'Acción recomendada',
    addMeasurement: 'Añadir medida',
    reportDefect: 'Reportar defecto',
    generateReport: 'Generar informe',
    overview: 'Resumen',
    compliant: 'Conforme',
    nonCompliant: 'No conforme',
    pass: 'Aprobado',
    warnings: 'Advertencias',
    failures: 'Fallos',
    isoCompliance: 'Conformidad ISO',
    
    // Settings
    appSettings: 'Configuración de la aplicación',
    appSettingsDescription: 'Configurar ajustes y preferencias de la aplicación',
    companyName: 'Nombre de la empresa',
    defaultLanguage: 'Idioma predeterminado',
    selectLanguage: 'Seleccionar idioma',
    dateFormat: 'Formato de fecha',
    selectDateFormat: 'Seleccionar formato de fecha',
    darkMode: 'Modo oscuro',
    saving: 'Guardando...',
    saveChanges: 'Guardar cambios',
    settingsSaved: 'Configuración guardada',
    settingsSavedSuccess: 'Tu configuración ha sido actualizada correctamente',
    notificationPreferences: 'Preferencias de notificación',
    notificationPreferencesDescription: 'Configurar cuándo y cómo recibes notificaciones',
    batchFailureAlerts: 'Alertas de fallo de lote',
    batchFailureAlertsDescription: 'Recibir notificación cuando un lote falla en el control de calidad',
    qualityThresholdAlerts: 'Alertas de umbral de calidad',
    qualityThresholdAlertsDescription: 'Recibir notificación cuando las medidas se acercan a umbrales críticos',
    newReportNotifications: 'Notificaciones de nuevos informes',
    newReportNotificationsDescription: 'Recibir notificación cuando se generan nuevos informes de calidad',
    systemUpdates: 'Actualizaciones del sistema',
    systemUpdatesDescription: 'Recibir notificación sobre actualizaciones y mantenimiento del sistema',
    notificationsSaved: 'Notificaciones guardadas',
    notificationsSavedSuccess: 'Tus preferencias de notificación han sido actualizadas correctamente',
    
    // Other
    unitOfMeasure: 'Unidad de medida',
    description: 'Descripción',
    image: 'Imagen',
    uploadImage: 'Subir imagen',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    confirm: 'Confirmar',
    back: 'Atrás',
    next: 'Siguiente',
    finish: 'Finalizar',
  }
};

const defaultLanguageContext: LanguageContextType = {
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
};

const LanguageContext = createContext<LanguageContextType>(defaultLanguageContext);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, params?: TranslationParams): string => {
    // @ts-ignore
    let text = translations[language][key] || key;
    
    // Replace parameters in the text if they exist
    if (params) {
      Object.keys(params).forEach(paramKey => {
        text = text.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
