
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpivcgfqapotixolzrfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaXZjZ2ZxYXBvdGl4b2x6cmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTEwOTMsImV4cCI6MjA2MjM2NzA5M30.Hmtq7q3pwJuj6IutiWXS-koEiENXsA-m5h9g2dcuM9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
